### PR TITLE
Refactor/nextgen

### PR DESCRIPTION
**Pull request by logicalparadox**
This is not yet ready to merge, however, good time for discussion...

Changes:
- removed mocha, added hydro, refactored tests
- coding style
- imported tea-extends as non-instance methods
- imported tea-merge (deep merge) as non-instance methods
- full browser support via component + karma tests

Discussion:
- normalize language: imported was include/exclude ... instance has only/except/require. We should figure out what makes most sense.

Waiting on:
- code review
- documentation normalization

### CODE REVIEW

**Comment by vesln** [comment]
Added browser tests with karma & hydro, also test coverage with istanbul

**Comment by logicalparadox** [comment]
Should I pull in my deep merge utility into this?

**Comment by vesln** [comment]
Yep!

**Comment by logicalparadox** [comment]
Update PR to represent current state. Please review.

I see two things remaining...
- normalize language
- docs

**Comment by vesln** [comment]
Looking good!

**Comment by logicalparadox** [comment]
can you refactor the testing to your latest hydro configs and give this another go...

**Pull request merged**
